/* tslint:disable:max-line-length */
import { Game } from './game';

export const GAMES: Game[] = [
  { id: 56, name: 'Resident Evil 4', players: 1, platform: 'Gamecube', releaseDate: 2005, rating: 'M - Mature', overview: 'U.S. agent Leon Kennedy has been tasked to look into the abduction of the President\'s daughter and his investigation has led him to a mysterious location in Europe. As Leon encounters unimaginable horrors, he must find out what is behind the terror.' },
  { id: 71, name: 'Viewtiful Joe', players: 1, platform: 'Gamecube', releaseDate: 2003, rating: 'T - Teen', overview: 'Joe is no ordinary man and Viewtiful Joe is no ordinary game. Capcom\'s new superhero action game mixes funky cartoon-style visuals with classic side-scrolling gameplay and introduces the world\'s quirkiest million dollar action hero. More than just any ordinary dude, Joe must transform into the ultimate superhero. It\'s up to you to activate the correct view mode like \\"slow\\" or \\"zoom in\\" in order to clobber your enemies with beautiful style. You can also speed up or slow down your visual effects for even more \\"viewtiful\\" moves. Viewtiful Joe mixes an innovative viewpoint with an amazing stunt-filled action movie universe.' },
  { id: 166, name: 'Mario Kart: Double Dash!!', players: 4, platform: 'Gamecube', releaseDate: 2003, rating: 'E - Everyone', overview: 'The Mushroom Kingdom just got a whole lot more hectic as Mario and friends double up for furious kart racing. This time around, each kart holds two racers that can switch places at any time, so choose from a huge cast of favorites and pair them up any way you see fit. The character in front handles the driving duties, while the character in the rear doles out damage with six normal items and eight special items that only specific characters can use. Get ready for some intense multiplayer mayhem with your favorite characters, including Mario, Luigi, Donkey Kong, Peach, Bowser, and Koopa.' },
  { id: 167, name: 'Mario Party 4', players: 4, platform: 'Gamecube', releaseDate: 2002, rating: 'E - Everyone', overview: 'Toad, Koopa, and other party-planning pranksters have hidden birthday presents for their closest friends inside the Party Cube. To win the presents, Mario, Yoshi, Peach, and other Mushroom Kingdom favorites will have to plunge into a circus of minigame trickery. As always, keep an eye out for Bowser and his trouble-making goons. Even Whomp and Thwomp have rockin\' surprises for you in their Extra Room. Packed with surprises, wild multiplayer action, and zany challenges, Mario Party 4 is your ticket to a good time.' },
  { id: 172, name: 'Metroid Prime', players: 1, platform: 'Gamecube', releaseDate: 2002, rating: 'T - Teen', overview: 'Ten years ago, beneath the surface of Planet Zebes, the mercenaries known as \\"Space Pirates\\" were defeated by interstellar bounty hunter Samus Aran. Descending to the very core of the pirate stronghold, Samus exterminated the energy based parasites called \\"Metroids\\" and defeated Mother Brain, the leader of the pirate hoarde. But the Space Pirates were far from finished. Several pirate research vessels were orbiting Zebes when Samus fought on the surface below. After the fall of Mother Brain, the ships escaped, with the hope of finding enough resources to rebuild their forces and take their revenge. After discovering a possible pirate colony on planet Talon IV, Samus has once again prepared for war, hoping to end the Pirate threat forever.' },
  { id: 174, name: 'The Legend of Zelda: The Wind Waker', players: 1, platform: 'Gamecube', releaseDate: 2003, rating: 'E - Everyone', overview: 'The game is set on a group of islands in a vast sea—a first for the series. The player controls Link, the protagonist of the Zelda series. He struggles against his nemesis, Ganondorf, for control of a sacred relic known as the Triforce. Link spends a large portion of the game sailing, traveling between islands, and traversing through dungeons and temples to gain the power necessary to defeat Ganondorf. He also spends time trying to find his little sister. The Wind Waker follows in the footsteps of Ocarina of Time and its sequel Majora\'s Mask, retaining the basic gameplay and control system from the two Nintendo 64 titles. A heavy emphasis is placed on using and controlling wind with a baton called the Wind Waker, which aids sailing and floating in air. Controversial during development for its use of cel shading graphics and younger Link character, The Wind Waker received acclaim on release and is one of the Nintendo GameCube\'s most popular games. * The \\"Tingle Tuner\\" is a special item allowing a second player to control the character Tingle if the system is connected to a Game Boy Advance by a link cable.' },
  { id: 2236, name: 'Super Mario Sunshine', players: 1, platform: 'Gamecube', releaseDate: 2002, rating: 'E - Everyone', overview: 'When Mario arrives on tropical Isle Delfino, the once-pristine island is polluted and plastered with graffiti. Even worse, he\'s being blamed for the mess! Now instead of enjoying a relaxing vacation, Mario has to clean up the place and track down the real culprit.' },
  { id: 2237, name: 'Luigi\'s Mansion', players: 1, platform: 'Gamecube', releaseDate: 2001, rating: 'E - Everyone', overview: 'Luigi\'s Won a Mansion! The bad news is that it\'s crawling with ghosts... and Mario seems to be trapped inside... Luigi\'s in for a spooktacular surprise as he creeps into the pitch-dark mansion he won, armed with only a flashlight and a vacuum custom-made for sucking up ghosts. Ghosts lurk in every nook and cranny. You\'ll have to master the Poltergust 3000 to vacuum them all up! Jewels, coins and cash are hidden throughout the mansion-and finding it all will be worth your while... You\'ll have to solve the mansion\'s many mysteries to catch a gallery of quirky ghouls, such as the fire-belching Mr. Luggs. Deep inside the mansion hide elusive boss ghosts like Bogmire, each with ghastly powers and a ghostly bone to pick with Luigi! After collecting special medals, you\'ll be able to shoot fire, water, and ice from your vacuum to unearth secrets and thwart extra-eerie ghosts!' },
  { id: 2258, name: 'Star Fox: Assault', players: 4, platform: 'Gamecube', releaseDate: 2005, rating: 'T - Teen', overview: 'Step into the guise of furry flyboy Fox McCloud as he returns to take on his deadliest enemy; wingmen Slippy Toad, Peppy Hare and Falco Lombardi are covering your back, as you take on hordes of intergalactic hostiles on land and in air. Hop into Arwings for aerial skirmishes and Landmaster Tanks for ground-based confrontations, or simply run around on foot dispensing laser justice; the searing single player adventure is a total blast, while the glorious four-way split-screen mode is sure to keep you and your friends coming back for more. With sniper rifles and rocket launchers, this is one Fox you don\'t want to mess with!' },
  { id: 2291, name: 'Kururin Squash', players: 1, platform: 'Gamecube', releaseDate: 2004, rating: 'E - Everyone', overview: 'Kururin Squash! is an action-puzzle video game developed by Eighting and published by Nintendo. It was released only in Japan on October 14, 2004. The game is the successor to Kururin Paradise and is the only title of the Kururin series with 3D computer graphics.' },
  { id: 2301, name: '1080: Avalanche', players: 4, platform: 'Gamecube', releaseDate: 2003, rating: 'E - Everyone', overview: '1080° Avalanche is a snowboarding game for the Nintendo GameCube, developed by Nintendo\'s in-house development studio, NST, and published by Nintendo. Avalanche is a sequel to 1080° Snowboarding for the Nintendo 64. The game has an emphasis on racing, rather than doing tricks, in contrast to other popular snowboarding games, such as the SSX series. It can output in 480p and Dolby Pro Logic II and supports four players on one GameCube as well as LAN play with up to four GameCubes.' },
];
